// 诗人行迹。stops 只放诗词 id，顺序即这个人走过的顺序（先地理、再年月，两者冲突时以诗里的时间为准）。
// 地图上画成一条缎带，站点可逐个点开；因为唐宋人走的是水驿与官道，
// 两站之间的直线距离常常只是实际行程的一半，所以线只说方向，不说里程。
//
// 字段约定：
//   id     唯一标识
//   name   线路名
//   poet   主角（主题线则写"多人"）
//   theme  一句话说这条线是什么
//   color  取自 PALETTE
//   stops  spots.js 里的真实 id，按行迹排序
//   notes  2-3 条，说这条线上发生了什么、为什么这样走
//   pace   一句话说这条线的节奏与读法

import { PALETTE } from './taxonomy.js';

export const ROUTES = [
  {
    id: 'libai',
    name: '李白行迹',
    poet: '李白',
    theme: '一生在路上：从三峡出川，过荆门、江汉、洛阳、庐山与皖南，最后走到剡中天姥',
    color: PALETTE.qing,
    stops: [
      'libai-zaofabaidicheng',
      'libai-dujingmensongbie',
      'libai-songmenghaoranzhiguangling',
      'libai-chunyeluocheng',
      'libai-xinglunan',
      'libai-jiangjinjiu',
      'libai-wanglushanpubu',
      'libai-qiupuge',
      'libai-duzuojingtingshan',
      'libai-wangtianmenshan',
      'libai-zengwanglun',
      'libai-songwenchushi-huangshan',
      'libai-wenwangchanglingzuoqian',
      'libai-mengtianlao',
    ],
    notes: [
      '开头两站是出川：白帝城下水、渡荆门别蜀，此后他的路几乎都顺长江与运河走，再没长住过蜀地',
      '两京各有一站：洛阳闻笛是过客，长安《行路难》是"直挂云帆济沧海"——被赐金放还之后才写得出这句话；嵩山的《将进酒》紧接其后',
      '中段那一串都在皖南一小片：庐山、秋浦、敬亭山、天门山、桃花潭、黄山，是他晚年往来最勤的地方；结尾的天姥山是梦里的，不是到过的——这条线到最后一站便从地图上离开了地图',
    ],
    pace: '按江流顺读一遍，再倒回来看洛阳与嵩山那两站，落差最清楚',
  },
  {
    id: 'dufu',
    name: '杜甫行迹',
    poet: '杜甫',
    theme: '从泰山下的少年意气，到长安陷落、成都借居、梓州闻捷，终于困在夔州',
    color: PALETTE.qingDeep,
    stops: [
      'dufu-wangyue',
      'dufu-chunwang',
      'dufu-yueye',
      'dufu-shihaoli',
      'dufu-maowuweiqiufeng',
      'dufu-shuxiang',
      'dufu-wenguanjunshouhenanhebei',
      'dufu-lvyeshuhuai',
      'dufu-qiuxing',
      'dufu-denggao',
    ],
    notes: [
      '《望岳》是二十几岁写的，"会当凌绝顶"；《登高》是五十几岁写的，"百年多病独登台"，两站相隔三十余年',
      '长安三站是陷贼中的同一年：《春望》看城，《月夜》想妻子，出城往西便是石壕村那一夜——差役半夜捉人，他只是"独与老翁别"',
      '成都两站一稳一叹（草堂与武侯祠），梓州听到官军收复河南河北是他一生写得最痛快的一首；此后顺江而下，忠州夜泊、夔州两首，地理上几乎不动了，诗却越写越远',
    ],
    pace: '十站顺读，不要跳站——这条线的意思全在前后对比里',
  },
  {
    id: 'sushi',
    name: '苏轼行迹',
    poet: '苏轼',
    theme: '一贬再贬，一路向南：杭州、密州、黄州、庐山、惠州、儋州',
    color: PALETTE.lvDeep,
    stops: [
      'sushi-yinhushang',
      'sushi-linjiangxian-songqianmufu',
      'sushi-jiangchengzi-jimeng',
      'sushi-jiangchengzi-mizhouchulie',
      'sushi-shuidiaogetou',
      'sushi-wangjiangnan-chaoranta',
      'sushi-busuanzi-huangzhou',
      'sushi-niannujiao-chibi',
      'sushi-dingfengbo',
      'sushi-tixilinbi',
      'sushi-guangzhoupujiansi',
      'sushi-dielianhua-chunjing',
      'sushi-shilizhi',
      'sushi-yeduhai',
    ],
    notes: [
      '杭州通判、密州知州还算迁转，乌台诗案后到黄州才是贬：初到定慧院写"缺月挂疏桐"，两年后在同一片江边写"大江东去"',
      '庐山西林寺那站是离开黄州、量移汝州的路上顺道游山，是这条线上少有的一段闲笔',
      '惠州、儋州两站在宋人眼里已是"天涯"，而他在那里写的是荔枝和渡海时的天色',
    ],
    pace: '沿纬度往下读，越到南边越要读慢；杭州、密州、黄州三处各有两三站，可以就地比一比',
  },
  {
    id: 'baijuyi-jiangzhou',
    name: '白居易与江州',
    poet: '白居易',
    theme: '从长安的讽喻诗，到贬江州司马，过忠州，再到杭州刺史修堤',
    color: PALETTE.lv,
    stops: [
      'baijuyi-maitanweng',
      'baijuyi-fudeguyuancaosongbie',
      'baijuyi-changhenge',
      'baijuyi-taixinglu',
      'baijuyi-pipaxing',
      'baijuyi-yexue',
      'baijuyi-wenliushijiu',
      'baijuyi-dalinsitaohua',
      'baijuyi-mujiangyin',
      'baijuyi-qiantanghuchunxing',
    ],
    notes: [
      '长安三站是同一个人的三副笔墨：《卖炭翁》自注"苦宫市也"，《赋得古原草送别》是十六岁的应试之作，《长恨歌》写在大明宫外 —— 讽喻、试帖、长歌都出自这一处',
      '江州三站是贬所的三副面孔：《琵琶行》"同是天涯沦落人"，《夜雪》只写"夜深知雪重"，《问刘十九》问一句"能饮一杯无"；顺路上庐山看桃花，说"人间四月芳菲尽"',
      '过忠州再往东就是杭州：任刺史时筑堤浚湖，白堤的名字从此而来 —— 同一个人，从被贬者写成了做事的人',
    ],
    pace: '十站四种身份，一站一站读身份的变化，比读风景要紧',
  },
  {
    id: 'wangwei',
    name: '王维行迹',
    poet: '王维',
    theme: '从长安出使到辋川归隐：送别在西北一线，山水都在终南山下',
    color: PALETTE.qingPale,
    stops: [
      'wangwei-jiuyuejiuri',
      'wangwei-songyuaner',
      'wangwei-shizhisaishang',
      'wangwei-guisongshanzuo',
      'wangwei-zhongnanshan',
      'wangwei-shanjuqiuming',
      'wangwei-zhuliguan',
      'wangwei-lucai',
      'wangwei-shanzhongsongbie',
      'wangwei-hanjianglinfan',
      'wangwei-songzizhoulishijun',
      'wangwei-niaomingjian',
    ],
    notes: [
      '开头三站往西北去：长安登高忆兄弟，渭城折柳送元二，再往外便是"大漠孤烟直"——他这一生走得最远的一趟是奉命出使',
      '中段六站几乎挤在一处：归嵩山、终南山，再往下就是辋川的四首（山居、竹里馆、鹿柴、山中送别）—— 同一个山谷的四种静，读起来才知道"静"也分深浅',
      '末尾三站是替别人看的山水：襄阳的汉江、梓州的山中、越州的云溪 —— 送人赴任、题人别业，写的仍是他自己的空山',
    ],
    pace: '前三站一口气读，辋川那几站要一首一首停；这条线的意思不在走了多远，在越走越静',
  },
  {
    id: 'wantang',
    name: '晚唐怅望',
    poet: '多人',
    theme: '一朝将尽时的眼光：长安的宫掖与雪、潼关咸阳的旧垒、池州宣州的秋山，末了是岭外幕府',
    color: PALETTE.lvPale,
    stops: [
      'lishangyin-legouyuan',
      'dumu-qiuxi',
      'luoyin-xue',
      'xuhun-qiurifuquetitongguanyilou',
      'xuhun-xianyangchengdonglou',
      'wentingyun-shangshanzaoxing',
      'dumu-qingming',
      'dumu-jiuriqishandenggao',
      'duxunhe-shanzhongguafu',
      'dumu-shanxing',
      'xuhun-xietingsongbie',
      'dumu-qianhuai',
      'dumu-zengbie-er',
      'weizhuang-taicheng',
      'lishangyin-wanqing',
    ],
    notes: [
      '开头三站都在长安：李商隐在乐游原说"只是近黄昏"，杜牧写深宫里的一把小扇，罗隐的《雪》直接问"长安有贫者，为瑞不宜多" —— 同一座城，三种冷',
      '出潼关、过咸阳、走商山，是晚唐人反复走的那条上京路；再往东南到池州、宣州，杜牧的秋山与杜荀鹤的山中寡妇挨在一起 —— 同一片山，一个看风景，一个看人',
      '扬州两站是杜牧回头看自己（"十年一觉扬州梦"），金陵的《台城》已在说"无情最是台城柳"；收尾一站远在桂州幕府，李商隐写"天意怜幽草" —— 这一朝的人，最后多半散在幕府里',
    ],
    pace: '不必按地理读，按"越看越远"读：先长安、再旧关、再江南的秋，末一站是岭外',
  },
  {
    id: 'biansai',
    name: '边塞一线',
    poet: '多人',
    theme: '从阳关外的大漠一路向东：碛中、玉门、凉州、延州、雁门、幽州',
    color: PALETTE.zhePale,
    stops: [
      'wangchangling-congjunxing',
      'censhen-qizhongzuo',
      'wanghan-liangzhouci',
      'censhen-fengrujingshi',
      'gaoshi-saishangtingchuidi',
      'liyi-yeshangshouxiangcheng',
      'censhen-xingjunjiurisichangan',
      'fanzhongyan-yujiaao',
      'wangchangling-chusai',
      'lihe-yanmentaishouxing',
      'gaoshi-yangezhixing',
      'chenziang-dengyouzhoutai',
      'gaoshi-yingzhouge',
    ],
    notes: [
      '这条线是唐代西北边防的实际走向：阳关、玉门是出关的两道门，门外是莫贺延碛，往东是河西大镇凉州，再往东到代州雁门、幽州蓟门',
      '中间的延州一站是北宋的，范仲淹守边时写的《渔家傲》；把它放进来，是因为唐宋两朝的边防线在这一段几乎重合',
      '末尾两站都在幽州：一首写"战士军前半死生"，一首写"前不见古人"，边塞诗到这里转成了怀古',
    ],
    pace: '从西往东顺读一遍就是回京的方向；《逢入京使》正好在这条路的中途',
  },
  {
    id: 'jinling',
    name: '金陵怀古',
    poet: '多人',
    theme: '六朝旧都到江北渡口：乌衣巷、秦淮、石头城、台城，过江是瓜洲与扬州',
    color: PALETTE.zhe,
    stops: [
      'liuyuxi-wuyixiang',
      'dumu-boqinhuai',
      'liuyuxi-shitoucheng',
      'weizhuang-taicheng',
      'zhudunru-xiangjianhuan-jinling',
      'wanganshi-guizhixiang-jinling',
      'xinqiji-shuilongyin-dengjiankang',
      'saduci-manjianghong-jinling',
      'dumu-jiangnanchun',
      'xinqiji-yongyule-beiguting',
      'wanganshi-bochuanguazhou',
      'jiangkui-yangzhouman',
    ],
    notes: [
      '城里七站相距都不过几里：唐人写乌衣巷、秦淮、石头城与台城，南渡之后朱敦儒在城上西楼哭"中原乱"，辛弃疾在赏心亭"栏杆拍遍"，元人萨都剌再来时只剩"蒋山青，秦淮碧"',
      '往东过到润州、镇江，北固亭上辛弃疾看的是江北；再一站瓜洲渡在对岸，王安石在船上回望钟山',
      '收尾的扬州是姜夔的：金兵过后的空城，"废池乔木，犹厌言兵"，这条线最后一句最冷',
    ],
    pace: '城里七站可以连着走，过江之后每站停一停，读的是同一片地方在不同朝代的样子',
  },
  {
    id: 'nandu',
    name: '南渡之路',
    poet: '多人',
    theme: '靖康之后南渡：从济南到乌江、金陵、临安、金华，再到鄂州军中、淮上、带湖与山阴',
    color: PALETTE.zhu,
    stops: [
      'liqingzhao-rumengling',
      'liqingzhao-yijianmei-hongou',
      'liqingzhao-xiarijueju',
      'zhudunru-xiangjianhuan-jinling',
      'liqingzhao-shengshengman',
      'liqingzhao-wulingchun',
      'yuefei-manjianghong',
      'yuefei-xiaochongshan',
      'zhangyuangan-hexinlang-songhubangheng',
      'zhangxiaoxiang-liuzhougetou',
      'xinqiji-pusaman-zaokou',
      'xinqiji-pozhenzi',
      'xinqiji-chounuer-boshan',
      'xinqiji-xijiangyue-huangshadaozhong',
      'xinqiji-qingyuan-an',
      'xinqiji-nanxiangzi-beiguting',
      'xinqiji-yongyule-beiguting',
      'luyou-linanchunyuchuji',
      'luyou-shufen',
      'luyou-chaitoufeng-hongsushou',
      'luyou-fengyudazuo',
      'luyou-shier',
    ],
    notes: [
      '李清照占五站：少年在章丘溪亭划船、在明水写"一种相思，两处闲愁"，过乌江叹"不肯过江东"，到临安"寻寻觅觅"，末了在金华写"载不动许多愁" —— 中间隔着国破、南渡与丧夫',
      '中段是几个北人的几种结局：朱敦儒在金陵城上哭"中原乱"，岳飞在鄂州军中一刚一柔（"怒发冲冠"与"知音少，弦断有谁听"），张元干送胡邦衡贬新州、张孝祥在淮上望见自家的国境线',
      '辛弃疾七站从造口的"中间多少行人泪"到北固亭的"廉颇老矣"，中间还夹着带湖闲居的两首（"却道天凉好个秋"与"稻花香里说丰年"）；陆游五站收尾，临安春雨、山阴书愤、沈园旧梦，一首"铁马冰河"在梦里，一首临终仍嘱"王师北定中原日"',
    ],
    pace: '这条线不必按地理看，按年份顺读——从北到南是一次，从壮到老是第二次',
  },
  {
    id: 'nanbian',
    name: '南贬之路',
    poet: '多人',
    theme: '一道往南的贬谪线：蓝关、永州、郴州、柳州、潮州、惠州，最后是海那边的儋州',
    color: PALETTE.mo,
    stops: [
      'hanyu-zuoqianzhilantian',
      'liuchangqing-changshaguojiayizhai',
      'liuzongyuan-jiangxue',
      'liuzongyuan-yuweng',
      'liuzongyuan-xiju',
      'qinguan-quexiaoxian',
      'huangtingjian-qingpingyue-chungui',
      'liuzongyuan-dengliuzhoushanlou',
      'liuzongyuan-yuhaochushangren',
      'hanyu-tilinlongsi',
      'sushi-shilizhi',
      'sushi-yeduhai',
    ],
    notes: [
      '这条线不按年月排，按纬度往南排：唐宋两朝的贬官走的其实是同一条路，蓝关出去，过湖南、岭南，尽头是海',
      '柳宗元占五站：永州十年写一个人独钓寒江、写溪上渔者"欸乃一声山水绿"、写自己"闲依农圃邻"，再贬柳州便只剩"海畔尖山似剑铓，秋来处处割愁肠"',
      '同一条路上的人反应各不相同：韩愈在蓝关交代后事（"好收吾骨瘴江边"），刘长卿过长沙只写贾谊旧宅的秋草，黄庭坚贬到宜州问"春归何处"，苏轼到惠州写荔枝、到儋州写渡海时的天色；秦观那一站是北宋的，处州再贬郴州，七夕词偏偏写"两情若是久长时"',
    ],
    pace: '从北往南一站一站读，注意越往南、诗里的"远"越不靠距离撑着，而靠一句"不恨"或"莫笑"顶住',
  },
  {
    id: 'yuanqu',
    name: '元曲行路',
    poet: '多人',
    theme: '元人的南北路：上京草原、燕城与大都、洛阳潼关骊山怀古、沛县还乡，再下赤壁、金陵与钱塘',
    color: PALETTE.jin,
    stops: [
      'saduci-shangjingjishi',
      'liuzhi-shanpoyang-yanchengshuhuai',
      'guanhanqing-sikuaiyu-bieqing',
      'wangshifu-shieryueguoyaominge',
      'wumingshi-zuitaiping-tangtangdayuan',
      'luzhi-dianqianhuan-xishan',
      'zhangyanghao-shanpoyang-luoyang',
      'zhangyanghao-shanpoyang-tongguan',
      'zhangyanghao-shanpoyang-weiyanghuaigu',
      'zhangyanghao-shanpoyang-lishan',
      'mazhiyuan-tianjingsha-qiusi',
      'suijingchen-gaozuhuanxiang',
      'aluwei-changongqu-yingxiong',
      'saduci-manjianghong-jinling',
      'luzhi-shouyangqu-biezhulianxiu',
      'zhulianxiu-shouyangqu-dalushuzhai',
      'qiaoji-zheguiling-jingxijishi',
      'xuzaisi-zheguiling-chunqing',
      'guanhanqing-yizhihua-hangzhoujing',
      'zhangkejiu-renyueyuan-shanzhongshushi',
      'zhengguangzu-changongqu',
    ],
    notes: [
      '起点在上京道上：元帝每年北巡，百官随行，所以元曲里有一片唐人没写过的草原 —— 而且是平视的，写的是乳酪和毡帘，不是征人泪；南下到燕城、大都，口气立刻换成市语，连"堂堂大元"也敢张口就骂',
      '中段四站是张养浩赴陕西赈灾途中的怀古，洛阳、潼关、未央、骊山一路往西看废宫与山河；再往东到沛县，睢景臣让一个乡下人把皇帝的威仪拆了',
      '末尾七站顺运河与长江南下：阿鲁威在蒲圻赤壁问"谁是英雄"，卢挚与珠帘秀在扬州江上一赠一答，到杭州关汉卿写"亡宋家旧华夷"，张可久却只肯在山中"数间茅舍"',
    ],
    pace: '二十一站里大半是"在路上"，适合连着读；到赤壁之后放慢，那几站是宋亡之后的江南',
  },
];


export const routeById = (id) => ROUTES.find((r) => r.id === id);
