// 诗人行迹。stops 只放诗词 id，顺序即这个人走过的顺序（先地理、再年月，两者冲突时以诗里的时间为准）。
// 地图上画成一条缎带，站点可逐个点开；因为唐宋人走的是水驿与官道，
// 两站之间的直线距离常常只是实际行程的一半，所以线只说方向，不说里程。
//
// 字段约定：
//   id     唯一标识
//   name   线路名
//   poet   主角（主题线则写"多人"）
//   theme  一句话说这条线是什么
//   color  取自 PALETTE
//   stops  spots.js 里的真实 id，按行迹排序
//   notes  2-3 条，说这条线上发生了什么、为什么这样走
//   pace   一句话说这条线的节奏与读法

import { PALETTE } from './taxonomy.js';

export const ROUTES = [
  {
    id: 'libai',
    name: '李白行迹',
    poet: '李白',
    theme: '一生在路上：从三峡出川，过荆门、江汉、洛阳、庐山与皖南，最后走到剡中天姥',
    color: PALETTE.qing,
    stops: [
      'libai-zaofabaidicheng',
      'libai-dujingmensongbie',
      'libai-songmenghaoranzhiguangling',
      'libai-chunyeluocheng',
      'libai-jiangjinjiu',
      'libai-wanglushanpubu',
      'libai-wangtianmenshan',
      'libai-zengwanglun',
      'libai-songwenchushi-huangshan',
      'libai-mengtianlao',
    ],
    notes: [
      '开头两站是出川：白帝城下水、渡荆门别蜀，此后他的路几乎都顺长江与运河走，再没长住过蜀地',
      '嵩山颍阳的《将进酒》在被赐金放还之后：同一个人，前半程写送别，后半程写"与尔同销万古愁"',
      '天门山、桃花潭、黄山挤在皖南一小片，是他晚年往来最勤的地方；结尾的天姥山是梦里的，不是到过的——这条线到最后一站便从地图上离开了地图',
    ],
    pace: '按江流顺读一遍，再倒回来看洛阳与嵩山那两站，落差最清楚',
  },
  {
    id: 'dufu',
    name: '杜甫行迹',
    poet: '杜甫',
    theme: '从泰山下的少年意气，到长安陷落、成都借居、梓州闻捷，终于困在夔州',
    color: PALETTE.qingDeep,
    stops: [
      'dufu-wangyue',
      'dufu-chunwang',
      'dufu-maowuweiqiufeng',
      'dufu-wenguanjunshouhenanhebei',
      'dufu-qiuxing',
      'dufu-denggao',
    ],
    notes: [
      '《望岳》是二十几岁写的，"会当凌绝顶"；《登高》是五十几岁写的，"百年多病独登台"，两站相隔三十余年',
      '长安到成都这一段是安史之乱中逃出来的，中间还隔着秦岭，实际走了一年多；在梓州听到官军收复河南河北，是他一生写得最痛快的一首',
      '最后两站都在夔州一带，地理上几乎不动了，诗却越写越远',
    ],
    pace: '六站顺读，不要跳站——这条线的意思全在前后对比里',
  },
  {
    id: 'sushi',
    name: '苏轼行迹',
    poet: '苏轼',
    theme: '一贬再贬，一路向南：杭州、密州、黄州、庐山、惠州、儋州',
    color: PALETTE.lvDeep,
    stops: [
      'sushi-yinhushang',
      'sushi-linjiangxian-songqianmufu',
      'sushi-jiangchengzi-jimeng',
      'sushi-jiangchengzi-mizhouchulie',
      'sushi-shuidiaogetou',
      'sushi-busuanzi-huangzhou',
      'sushi-niannujiao-chibi',
      'sushi-dingfengbo',
      'sushi-tixilinbi',
      'sushi-guangzhoupujiansi',
      'sushi-shilizhi',
      'sushi-yeduhai',
    ],
    notes: [
      '杭州通判、密州知州还算迁转，乌台诗案后到黄州才是贬：初到定慧院写"缺月挂疏桐"，两年后在同一片江边写"大江东去"',
      '庐山西林寺那站是离开黄州、量移汝州的路上顺道游山，是这条线上少有的一段闲笔',
      '惠州、儋州两站在宋人眼里已是"天涯"，而他在那里写的是荔枝和渡海时的天色',
    ],
    pace: '沿纬度往下读，越到南边越要读慢；杭州、密州、黄州三处各有两三站，可以就地比一比',
  },
  {
    id: 'baijuyi-jiangzhou',
    name: '白居易与江州',
    poet: '白居易',
    theme: '从长安的讽喻诗，到贬江州司马，过忠州，再到杭州刺史修堤',
    color: PALETTE.lv,
    stops: [
      'baijuyi-maitanweng',
      'baijuyi-taixinglu',
      'baijuyi-pipaxing',
      'baijuyi-wenliushijiu',
      'baijuyi-mujiangyin',
      'baijuyi-qiantanghuchunxing',
    ],
    notes: [
      '前两站都是新乐府：《卖炭翁》自注"苦宫市也"，《太行路》借夫妻说君臣 —— 正是让他后来被贬的那一类诗',
      '中间两站都在江州：《琵琶行》"同是天涯沦落人"，《问刘十九》只问一句"能饮一杯无"，贬所的日子两副面孔',
      '过忠州再往东就是杭州：任刺史时筑堤浚湖，白堤的名字从此而来 —— 同一个人，从被贬者写成了做事的人',
    ],
    pace: '六站四种身份，一站一站读身份的变化，比读风景要紧',
  },
  {
    id: 'biansai',
    name: '边塞一线',
    poet: '多人',
    theme: '从阳关外的大漠一路向东：碛中、玉门、凉州、延州、雁门、幽州',
    color: PALETTE.zhePale,
    stops: [
      'wangchangling-congjunxing',
      'censhen-qizhongzuo',
      'wangzhihuan-liangzhouci',
      'censhen-fengrujingshi',
      'fanzhongyan-yujiaao',
      'wangchangling-chusai',
      'gaoshi-yangezhixing',
      'chenziang-dengyouzhoutai',
    ],
    notes: [
      '这条线是唐代西北边防的实际走向：阳关、玉门是出关的两道门，门外是莫贺延碛，往东是河西大镇凉州，再往东到代州雁门、幽州蓟门',
      '中间的延州一站是北宋的，范仲淹守边时写的《渔家傲》；把它放进来，是因为唐宋两朝的边防线在这一段几乎重合',
      '末尾两站都在幽州：一首写"战士军前半死生"，一首写"前不见古人"，边塞诗到这里转成了怀古',
    ],
    pace: '从西往东顺读一遍就是回京的方向；《逢入京使》正好在这条路的中途',
  },
  {
    id: 'jinling',
    name: '金陵怀古',
    poet: '多人',
    theme: '六朝旧都到江北渡口：乌衣巷、秦淮、石头城、台城，过江是瓜洲与扬州',
    color: PALETTE.zhe,
    stops: [
      'liuyuxi-wuyixiang',
      'dumu-boqinhuai',
      'liuyuxi-shitoucheng',
      'weizhuang-taicheng',
      'zhudunru-xiangjianhuan-jinling',
      'xinqiji-shuilongyin-dengjiankang',
      'saduci-manjianghong-jinling',
      'dumu-jiangnanchun',
      'xinqiji-yongyule-beiguting',
      'wanganshi-bochuanguazhou',
      'jiangkui-yangzhouman',
    ],
    notes: [
      '城里七站相距都不过几里：唐人写乌衣巷、秦淮、石头城与台城，南渡之后朱敦儒在城上西楼哭"中原乱"，辛弃疾在赏心亭"栏杆拍遍"，元人萨都剌再来时只剩"蒋山青，秦淮碧"',
      '往东过到润州、镇江，北固亭上辛弃疾看的是江北；再一站瓜洲渡在对岸，王安石在船上回望钟山',
      '收尾的扬州是姜夔的：金兵过后的空城，"废池乔木，犹厌言兵"，这条线最后一句最冷',
    ],
    pace: '城里七站可以连着走，过江之后每站停一停，读的是同一片地方在不同朝代的样子',
  },
  {
    id: 'nandu',
    name: '南渡之路',
    poet: '多人',
    theme: '靖康之后南渡：从济南到乌江、金陵、临安、金华，再到鄂州军中、淮上、带湖与山阴',
    color: PALETTE.zhu,
    stops: [
      'liqingzhao-rumengling',
      'liqingzhao-xiarijueju',
      'zhudunru-xiangjianhuan-jinling',
      'liqingzhao-shengshengman',
      'liqingzhao-wulingchun',
      'yuefei-manjianghong',
      'yuefei-xiaochongshan',
      'zhangxiaoxiang-liuzhougetou',
      'xinqiji-pusaman-zaokou',
      'xinqiji-pozhenzi',
      'xinqiji-qingyuan-an',
      'xinqiji-nanxiangzi-beiguting',
      'xinqiji-yongyule-beiguting',
      'luyou-shufen',
      'luyou-fengyudazuo',
      'luyou-shier',
    ],
    notes: [
      '李清照占四站：少年在章丘溪亭划船，过乌江叹"不肯过江东"，到临安"寻寻觅觅"，末了在金华写"载不动许多愁" —— 中间隔着国破、南渡与丧夫',
      '鄂州军中两首是一刚一柔：《满江红》"怒发冲冠"，《小重山》却说"知音少，弦断有谁听"；张孝祥在淮上望见的，是宋金划界之后自家的国境线',
      '辛弃疾四站从造口的"中间多少行人泪"到北固亭的"廉颇老矣"，陆游三站都在山阴：一首"铁马冰河"在梦里，一首临终仍嘱"王师北定中原日"',
    ],
    pace: '这条线不必按地理看，按年份顺读——从北到南是一次，从壮到老是第二次',
  },
  {
    id: 'nanbian',
    name: '南贬之路',
    poet: '多人',
    theme: '一道往南的贬谪线：蓝关、永州、郴州、柳州、潮州、惠州，最后是海那边的儋州',
    color: PALETTE.mo,
    stops: [
      'hanyu-zuoqianzhilantian',
      'liuzongyuan-jiangxue',
      'liuzongyuan-yuweng',
      'qinguan-quexiaoxian',
      'liuzongyuan-dengliuzhoushanlou',
      'liuzongyuan-yuhaochushangren',
      'hanyu-tilinlongsi',
      'sushi-shilizhi',
      'sushi-yeduhai',
    ],
    notes: [
      '这条线不按年月排，按纬度往南排：唐宋两朝的贬官走的其实是同一条路，蓝关出去，过湖南、岭南，尽头是海',
      '柳宗元占四站：永州十年写一个人独钓寒江、写溪上渔者"欸乃一声山水绿"，再贬柳州便只剩"海畔尖山似剑铓，秋来处处割愁肠"',
      '同一条路上的人反应各不相同：韩愈在蓝关交代后事（"好收吾骨瘴江边"），苏轼到惠州写荔枝、到儋州写渡海时的天色；秦观那一站是北宋的，处州再贬郴州，七夕词偏偏写"两情若是久长时"',
    ],
    pace: '从北往南一站一站读，注意越往南、诗里的"远"越不靠距离撑着，而靠一句"不恨"或"莫笑"顶住',
  },
  {
    id: 'yuanqu',
    name: '元曲行路',
    poet: '多人',
    theme: '元人的南北路：上京草原、燕城与大都、洛阳潼关骊山怀古、沛县还乡，再下赤壁、金陵与钱塘',
    color: PALETTE.jin,
    stops: [
      'saduci-shangjingjishi',
      'liuzhi-shanpoyang-yanchengshuhuai',
      'guanhanqing-sikuaiyu-bieqing',
      'wangshifu-shieryueguoyaominge',
      'wumingshi-zuitaiping-tangtangdayuan',
      'luzhi-dianqianhuan-xishan',
      'zhangyanghao-shanpoyang-luoyang',
      'zhangyanghao-shanpoyang-tongguan',
      'zhangyanghao-shanpoyang-weiyanghuaigu',
      'zhangyanghao-shanpoyang-lishan',
      'mazhiyuan-tianjingsha-qiusi',
      'suijingchen-gaozuhuanxiang',
      'aluwei-changongqu-yingxiong',
      'saduci-manjianghong-jinling',
      'luzhi-shouyangqu-biezhulianxiu',
      'zhulianxiu-shouyangqu-dalushuzhai',
      'qiaoji-zheguiling-jingxijishi',
      'xuzaisi-zheguiling-chunqing',
      'guanhanqing-yizhihua-hangzhoujing',
      'zhangkejiu-renyueyuan-shanzhongshushi',
      'zhengguangzu-changongqu',
    ],
    notes: [
      '起点在上京道上：元帝每年北巡，百官随行，所以元曲里有一片唐人没写过的草原 —— 而且是平视的，写的是乳酪和毡帘，不是征人泪；南下到燕城、大都，口气立刻换成市语，连"堂堂大元"也敢张口就骂',
      '中段四站是张养浩赴陕西赈灾途中的怀古，洛阳、潼关、未央、骊山一路往西看废宫与山河；再往东到沛县，睢景臣让一个乡下人把皇帝的威仪拆了',
      '末尾七站顺运河与长江南下：阿鲁威在蒲圻赤壁问"谁是英雄"，卢挚与珠帘秀在扬州江上一赠一答，到杭州关汉卿写"亡宋家旧华夷"，张可久却只肯在山中"数间茅舍"',
    ],
    pace: '二十一站里大半是"在路上"，适合连着读；到赤壁之后放慢，那几站是宋亡之后的江南',
  },
];


export const routeById = (id) => ROUTES.find((r) => r.id === id);
