export const CASE_ID = 'echo-gallery';

export const caseData = {
  id: CASE_ID,
  version: 1,
  title: '回声画廊：消失的原作',
  subtitle: '校庆艺术展调包事件',
  startTime: '17:42',
  maxAccusations: 3,
  opening: '校庆艺术展开展前十八分钟，冠军作品《逆光跑道》被发现是一幅高精度复制品。原作不知所踪。',
  truth: {
    culpritId: 'lin-xia',
    motiveId: 'hide-coauthorship',
    locationId: 'old-studio',
    requiredEvidenceIds: ['print-dots', 'sw-signature', 'print-log', 'access-log', 'shared-sketch', 'original-painting'],
    summary: '林夏为掩盖《逆光跑道》由她与苏晚共同创作的事实，在闭馆后利用打印室制作复制品，换下原作并藏进旧画材室的封闭画柜。她没有销毁作品，只想在校庆和评奖结束后取回。',
  },
  locations: {
    gallery: {
      id: 'gallery',
      name: '校庆展厅',
      shortName: '展厅',
      description: '布展刚刚暂停。复制品仍挂在主墙上，现场保留着最后一轮布展的痕迹。',
      image: '/images/location-gallery.jpg',
      hotspots: ['frame-backing', 'print-surface', 'setup-photo'],
    },
    'print-room': {
      id: 'print-room',
      name: '数字打印室',
      shortName: '打印室',
      description: '大幅面打印机仍有余温，值班记录显示昨晚有人临时申请使用。',
      image: '/images/location-print-room.jpg',
      hotspots: ['printer-console', 'waste-bin'],
    },
    corridor: {
      id: 'corridor',
      name: '美术楼东翼',
      shortName: '东翼走廊',
      description: '展厅、打印室和旧画材室在同一条走廊上，门禁终端记录了晚间通行。',
      image: '/images/location-corridor.jpg',
      hotspots: ['access-terminal', 'notice-board'],
    },
    'old-studio': {
      id: 'old-studio',
      name: '旧画材室',
      shortName: '画材室',
      description: '一间很少开放的旧储藏室。北侧画柜上了锁，空气里有保护漆的气味。',
      image: '/images/location-storage.jpg',
      hotspots: ['checkout-book', 'locked-cabinet'],
      unlockEvidenceIds: ['access-log', 'shared-sketch'],
    },
  },
  hotspots: {
    'frame-backing': {
      id: 'frame-backing', locationId: 'gallery', label: '画框背板', icon: 'frame', x: 42, y: 31, width: 6, height: 39,
      title: '被重新开启的画框', description: '背板卡扣有两组方向相反的压痕，说明画框在完成装裱后又被打开过。',
      evidenceId: 'frame-marks', timelineId: 'time-frame-opened',
    },
    'print-surface': {
      id: 'print-surface', locationId: 'gallery', label: '复制品表面', icon: 'search', x: 49, y: 40, width: 14, height: 22,
      title: '不属于颜料的网点', description: '侧光下能看到规则的青、品红、黄网点。这不是颜料层，而是大幅面喷墨输出。',
      evidenceId: 'print-dots', requiresEvidenceIds: ['frame-marks'], timelineId: 'time-copy-confirmed',
    },
    'setup-photo': {
      id: 'setup-photo', locationId: 'gallery', label: '布展照片', icon: 'camera', x: 8, y: 69, width: 20, height: 19,
      title: '角落里的铅笔缩写', description: '志愿者下午拍的布展照片中，原作右下角有一行很淡的“S.W.”，现在的复制品上没有。',
      evidenceId: 'sw-signature', timelineId: 'time-setup-photo',
    },
    'printer-console': {
      id: 'printer-console', locationId: 'print-room', label: '打印机任务记录', icon: 'printer', x: 46, y: 37, width: 31, height: 37,
      title: '闭馆后的大幅面任务', description: '昨晚 20:48 输出过一张 90×120 厘米的高精度图像，文件名是“runway_final_v7”。',
      evidenceId: 'print-log', requiresEvidenceIds: ['print-dots'], timelineId: 'time-print-job',
    },
    'waste-bin': {
      id: 'waste-bin', locationId: 'print-room', label: '废纸篓', icon: 'trash', x: 76, y: 70, width: 16, height: 18,
      title: '被丢弃的色彩校样', description: '一张颜色偏暗的《逆光跑道》局部校样。背面写着“再亮 6%”。',
      evidenceId: 'color-proof', requiresEvidenceIds: ['print-dots'], timelineId: 'time-color-proof',
    },
    'access-terminal': {
      id: 'access-terminal', locationId: 'corridor', label: '门禁终端', icon: 'key', x: 74, y: 32, width: 12, height: 32,
      title: '与口供冲突的门禁记录', description: '林夏的学生卡在 20:41 进入东翼，21:16 才离开。她此前说自己八点前已经回宿舍。',
      evidenceId: 'access-log', requiresEvidenceIds: ['print-log'], timelineId: 'time-access',
    },
    'notice-board': {
      id: 'notice-board', locationId: 'corridor', label: '值班公告栏', icon: 'clipboard', x: 11, y: 26, width: 22, height: 39,
      title: '临时调整的值班安排', description: '陈墨昨晚原本负责闭馆，但 20:30 后被老师叫去礼堂搬设备。他并不在调包时间段。',
      evidenceId: 'volunteer-alibi', timelineId: 'time-volunteer-left',
    },
    'checkout-book': {
      id: 'checkout-book', locationId: 'old-studio', label: '画材室借用册', icon: 'book', x: 10, y: 66, width: 25, height: 18,
      title: '被忽略的借用记录', description: '林夏三天前借用了旧画材室的北侧画柜，归还日期写在校庆结束后。',
      evidenceId: 'studio-record', timelineId: 'time-studio-record',
    },
    'locked-cabinet': {
      id: 'locked-cabinet', locationId: 'old-studio', label: '北侧画柜', icon: 'lock', x: 48, y: 22, width: 37, height: 63,
      title: '画柜里的原作', description: '画柜深处包着无酸纸的正是《逆光跑道》原作。右下角的“S.W.”仍然清晰可见。',
      evidenceId: 'original-painting', requiresEvidenceIds: ['studio-record', 'shared-sketch'], timelineId: 'time-original-found',
    },
  },
  evidence: {
    'frame-marks': { id: 'frame-marks', name: '画框二次开启痕迹', category: '物证', image: '/images/evidence-frame.jpg', summary: '装裱完成后，背板至少又被打开过一次。', source: '校庆展厅' },
    'print-dots': { id: 'print-dots', name: '复制品印刷网点', category: '物证', image: '/images/evidence-print-dots.jpg', summary: '墙上的“作品”是大幅面喷墨复制品。', source: '校庆展厅' },
    'sw-signature': { id: 'sw-signature', name: '原作上的 S.W.', category: '影像', image: '/images/evidence-signature.jpg', summary: '布展照片显示原作曾有苏晚的缩写。', source: '校庆展厅' },
    'print-log': { id: 'print-log', name: '大幅面打印记录', category: '记录', image: '/images/evidence-print-log.jpg', summary: '调包前夜打印过同尺寸高清文件。', source: '数字打印室' },
    'color-proof': { id: 'color-proof', name: '废弃色彩校样', category: '物证', image: '/images/evidence-proof.jpg', summary: '有人对复制品做过至少一次色彩调整。', source: '数字打印室' },
    'access-log': { id: 'access-log', name: '林夏门禁记录', category: '门禁', image: '/images/evidence-access.jpg', summary: '林夏在调包时段进入过美术楼东翼。', source: '美术楼东翼' },
    'volunteer-alibi': { id: 'volunteer-alibi', name: '陈墨值班调整', category: '记录', image: '/images/evidence-duty.jpg', summary: '陈墨在关键时间段不在东翼。', source: '美术楼东翼' },
    'shared-sketch': { id: 'shared-sketch', name: '共同创作草图', category: '物证', image: '/images/evidence-sketch.jpg', summary: '苏晚保存的草图证明作品由两人共同构思。', source: '苏晚' },
    'studio-record': { id: 'studio-record', name: '画材室借用记录', category: '记录', image: '/images/evidence-record.jpg', summary: '林夏提前借用了藏有原作的画柜。', source: '旧画材室' },
    'original-painting': { id: 'original-painting', name: '《逆光跑道》原作', category: '物证', image: '/images/evidence-original.jpg', summary: '原作完好藏在画柜中，并保留 S.W. 缩写。', source: '旧画材室' },
  },
  timeline: {
    'time-studio-record': { id: 'time-studio-record', order: 10, time: '三日前', title: '借用北侧画柜', detail: '林夏提前登记了画柜使用权。' },
    'time-volunteer-left': { id: 'time-volunteer-left', order: 20, time: '昨晚 20:30', title: '陈墨离开东翼', detail: '临时前往礼堂搬运设备。' },
    'time-access': { id: 'time-access', order: 30, time: '昨晚 20:41', title: '林夏刷卡进入东翼', detail: '与她“八点前离校”的口供冲突。' },
    'time-print-job': { id: 'time-print-job', order: 40, time: '昨晚 20:48', title: '打印复制品', detail: '输出与原作同尺寸的高清图像。' },
    'time-color-proof': { id: 'time-color-proof', order: 50, time: '昨晚 20:53', title: '调整复制品色彩', detail: '废弃校样上留有亮度修改笔记。' },
    'time-frame-opened': { id: 'time-frame-opened', order: 60, time: '昨晚 21:02', title: '画框被重新开启', detail: '背板卡扣留下第二组压痕。' },
    'time-setup-photo': { id: 'time-setup-photo', order: 70, time: '今日 16:38', title: '布展照片确认原作', detail: '照片记录了原作和右下角的 S.W. 缩写。' },
    'time-copy-confirmed': { id: 'time-copy-confirmed', order: 80, time: '今日 17:47', title: '确认展品为复制品', detail: '表面发现规则喷墨网点。' },
    'time-original-found': { id: 'time-original-found', order: 90, time: '今日 18:16', title: '找到原作', detail: '原作完好藏在旧画材室北侧画柜。' },
  },
  characters: {
    'lin-xia': {
      id: 'lin-xia', name: '林夏', role: '获奖者 · 视觉传达系', image: '/images/character-lin-xia.jpg', color: '#a6513d',
      intro: '作品《逆光跑道》的署名作者。回答克制，但对布展时间格外敏感。',
      quickQuestions: ['你最后一次见到原作是什么时候？', '你昨晚来过美术楼吗？', 'S.W. 是什么意思？'],
      allowedFactIds: ['lin-last-saw', 'lin-access-denial', 'lin-access-admission', 'lin-coauthor-pressure', 'lin-confession'],
    },
    'su-wan': {
      id: 'su-wan', name: '苏晚', role: '林夏前搭档 · 油画系', image: '/images/character-su-wan.jpg', color: '#387a7b',
      intro: '曾与林夏共同创作，评奖前突然退出项目。她手里似乎还留着早期材料。',
      quickQuestions: ['你参与过《逆光跑道》吗？', '为什么退出项目？', '你保留了什么材料？'],
      allowedFactIds: ['su-coauthor', 'su-left-project', 'su-sketch'],
    },
    'he-yu': {
      id: 'he-yu', name: '何屿', role: '比赛第二名 · 摄影系', image: '/images/character-he-yu.jpg', color: '#5a6a92',
      intro: '公开质疑过评审结果，但他更在意创作是否诚实，而不是名次。',
      quickQuestions: ['你为什么质疑评审？', '昨晚你在哪里？', '你拍到过什么？'],
      allowedFactIds: ['he-criticism', 'he-alibi', 'he-photo'],
    },
    'chen-mo': {
      id: 'chen-mo', name: '陈墨', role: '展览志愿者 · 建筑系', image: '/images/character-chen-mo.jpg', color: '#7b6747',
      intro: '持有展厅备用钥匙，是最容易被怀疑的人。他一直强调自己昨晚临时离岗。',
      quickQuestions: ['备用钥匙一直在你手里吗？', '为什么临时离岗？', '谁知道旧画材室？'],
      allowedFactIds: ['chen-key', 'chen-alibi', 'chen-studio'],
    },
  },
  facts: {
    'lin-last-saw': { responseId: 'lin-last-saw', characterId: 'lin-xia', text: '我最后一次见到原作是在下午装裱完成时。之后我就没再碰过画框。', requiresEvidenceIds: [] },
    'lin-access-denial': { responseId: 'lin-access-denial', characterId: 'lin-xia', text: '昨晚我没有回美术楼，八点前就回宿舍了。你可以去查。', requiresEvidenceIds: [] },
    'lin-access-admission': { responseId: 'lin-access-admission', characterId: 'lin-xia', text: '好，我昨晚确实回来过。我去打印室补了一张展签，但我没有动原作。', requiresEvidenceIds: ['access-log'] },
    'lin-coauthor-pressure': { responseId: 'lin-coauthor-pressure', characterId: 'lin-xia', text: 'S.W. 是苏晚。她确实参与过早期构图，但最后的成品是我完成的。', requiresEvidenceIds: ['sw-signature'] },
    'lin-confession': { responseId: 'lin-confession', characterId: 'lin-xia', text: '好，我承认昨晚回来过。我只想先把原作收起来，等校庆后再处理署名问题。我没打算毁掉它。', requiresEvidenceIds: ['access-log', 'shared-sketch', 'original-painting'] },
    'su-coauthor': { responseId: 'su-coauthor', characterId: 'su-wan', text: '《逆光跑道》的构图和人物关系是我们一起定的。右下角的 S.W. 是我在底稿阶段留下的。', requiresEvidenceIds: ['sw-signature'] },
    'su-left-project': { responseId: 'su-left-project', characterId: 'su-wan', text: '林夏说双署名会影响她的奖学金申请。我不想在评奖前公开争吵，所以退出了。', requiresEvidenceIds: ['sw-signature'] },
    'su-sketch': { responseId: 'su-sketch', characterId: 'su-wan', text: '我保留了共同草图。日期、配色和人物位置都能对应原作，你可以拿去核对。', requiresEvidenceIds: ['sw-signature'], grantsEvidenceId: 'shared-sketch' },
    'he-criticism': { responseId: 'he-criticism', characterId: 'he-yu', text: '我质疑的不是她得奖，而是作品叙事风格突然变了，像是两个人的语言硬拼在一起。', requiresEvidenceIds: [] },
    'he-alibi': { responseId: 'he-alibi', characterId: 'he-yu', text: '昨晚九点我在摄影棚做校庆直播测试，原始素材的时间码可以证明。', requiresEvidenceIds: [] },
    'he-photo': { responseId: 'he-photo', characterId: 'he-yu', text: '我下午拍过布展现场。原作右下角确实有一行很淡的字，复制品上没有。', requiresEvidenceIds: ['sw-signature'] },
    'chen-key': { responseId: 'chen-key', characterId: 'chen-mo', text: '备用钥匙在值班盒里，但布展成员都知道盒子密码。仅凭钥匙不能说明是谁。', requiresEvidenceIds: [] },
    'chen-alibi': { responseId: 'chen-alibi', characterId: 'chen-mo', text: '八点半后我一直在礼堂。值班调整和搬运签到都在公告栏上。', requiresEvidenceIds: [] },
    'chen-studio': { responseId: 'chen-studio', characterId: 'chen-mo', text: '旧画材室很少开放，借用册放在门边。只有登记过的人能领到画柜钥匙。', requiresEvidenceIds: ['access-log'] },
  },
  confrontations: {
    'lin-xia:access-log': { targetId: 'lin-xia', evidenceId: 'access-log', responseId: 'lin-access-admission', message: '林夏的口供被门禁记录推翻。她承认昨晚回来过，却仍回避原作去向。' },
    'lin-xia:shared-sketch': { targetId: 'lin-xia', evidenceId: 'shared-sketch', responseId: 'lin-confession', requiresEvidenceIds: ['access-log', 'original-painting'], message: '共同草图与找回的原作证明署名争议才是调包动机。林夏终于承认调包。' },
    'su-wan:sw-signature': { targetId: 'su-wan', evidenceId: 'sw-signature', responseId: 'su-sketch', grantsEvidenceId: 'shared-sketch', message: '苏晚确认缩写属于她，并交出了共同创作草图。' },
    'chen-mo:volunteer-alibi': { targetId: 'chen-mo', evidenceId: 'volunteer-alibi', responseId: 'chen-alibi', message: '值班记录排除了陈墨在关键时段实施调包的可能。' },
  },
  accusationOptions: {
    motives: [
      { id: 'hide-coauthorship', label: '掩盖共同创作与署名争议' },
      { id: 'revenge-ranking', label: '报复比赛评审结果' },
      { id: 'protect-exhibit', label: '保护作品避免展览损坏' },
    ],
    locations: [
      { id: 'old-studio', label: '旧画材室北侧画柜' },
      { id: 'print-room', label: '数字打印室设备柜' },
      { id: 'corridor', label: '东翼走廊吊顶' },
    ],
  },
};

export function visibleCaseMetadata() {
  return {
    id: caseData.id,
    version: caseData.version,
    title: caseData.title,
    subtitle: caseData.subtitle,
    opening: caseData.opening,
    startTime: caseData.startTime,
    maxAccusations: caseData.maxAccusations,
  };
}
